export const ICON = {
	COMPRESS   : 'i-fa6-solid:minimize',
	DOWNLOAD   : 'i-fa6-solid:download',
	REMOVE     : 'i-fa6-solid:xmark',
	MORE       : 'i-fa6-solid:plus',
	HELP       : 'i-fa6-solid:circle-question',
	RESET      : 'i-fa6-solid:rotate-left',
	LOAD       : 'i-fa6-solid:spinner',
	FILE       : 'i-fa6-solid:file',
	FILE_ZIP   : 'i-fa6-solid:file-zipper',
	FILE_CODE  : 'i-fa6-solid:file-code',
	FILE_PDF   : 'i-fa6-solid:file-pdf',
	FILE_IMAGE : 'i-fa6-solid:file-image',
	FILE_VIDEO : 'i-fa6-solid:file-video',
}
